id: IB6CBDBDC
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T00:48:58.478945'
last_modified: '2022-06-19T00:48:58.478958'
parser: null
source_metadata:
  title: A mes zhabss (1597–1659) Record of Teachings Received, parts I-XI
  author: a myes zhabs ngag dbang kun dga bsod nams/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2015-07-05); Wylie pagination; unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Guru Lama, Sachen International, Kathmandu (Nepal) (si)
  - Editorial process:Mathias Fermer (mf), bsam grub/ (Dharamsala) (sdr)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:bsam grub/ (sdr)
  text_witnesses: https://sakyaresearch.org/sources/602
  bases:
    6a07:
      title: A mes zhabss (1597–1659) Record of Teachings Received, parts I-XI
      order: 1
      base_file: 6a07.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
